version: '3.4'
services:
  activemq-1:
    build: .
    image: jason-activemq
    ports:  
      - "8161:8161"
      - "61616:61616"
    volumes:  
      - /home/activemq/conf:/opt/activemq/conf
      - /home/activemq/data:/opt/activemq/data
    restart: always
    