version: '3.4'
services:
  activemq-1:
    image: activemq
    port:
      - "8161:8161"
      - "61616:61616"
    volumnes:
      - /home/activemq/conf:/opt/activemq/conf
      - /home/activemq/data:/opt/activemq/data
    restart: always
    